name: Generate Public File List

on:
  push:
    branches: [main]

jobs:
  generate-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run indexing script
      run: python generate_list.py

    - name: Commit updated list
      run: |
        git config --global user.name "0xarchit"
        git config --global user.email "0xarchit@gmail.com"
        git add list.html
        git commit -m "Update /list page [skip ci]" || echo "No changes to commit"
        git push
